server:
  port: 8002
security:
  basic:
    enabled: true
  user:
    name: minnikanti
    password: minnikanti
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/minnikanti/spring-cloudconfig
          search-paths:
          - station*
          repos:
            pref:
              pattern:
              - '*/pref'
              uri: https://github.com/minnikanti/spring-cloudconfig-perf
              search-paths:
              - station*
  jackson:
    serialization:
      indent-output: true